# Destino: alansenairj/targeting-service -> .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: alansenairj/togglemaster-gitops/.github/workflows/ci-python.yml@main

  cd:
    needs: ci
    permissions:
      contents: read
      id-token: write
    uses: alansenairj/togglemaster-gitops/.github/workflows/cd-container.yml@main
    with:
      service: targeting-service
      ecr_repository: togglemaster/targeting-service
      gitops_path: apps/targeting
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
